version: '3.8'
services:
  app-blue:
    image: sinduke/vaporpreview:latest
    environment:
      DATABASE_HOST: 1Panel-postgresql-jrTE
      DATABASE_NAME: vapor_database
      DATABASE_USERNAME: user_3nr7F8
      DATABASE_PASSWORD: password_FnaEAc
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
    networks:
      - 1panel-network

  app-green:
    image: sinduke/vaporpreview:latest
    environment:
      DATABASE_HOST: 1Panel-postgresql-jrTE
      DATABASE_NAME: vapor_database
      DATABASE_USERNAME: user_3nr7F8
      DATABASE_PASSWORD: password_FnaEAc
    ports:
      - "8081:8080"
    deploy:
      replicas: 0
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true