services:
  app-blue:
    image: sinduke/vaporpreview:latest
    environment:
      DATABASE_HOST: 1Panel-postgresql-jrTE
      DATABASE_NAME: vapor_database
      DATABASE_USERNAME: user_3nr7F8
      DATABASE_PASSWORD: password_FnaEAc
      TZ: Asia/Shanghai
    ports:
      - "8080:8080"
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
    restart: on-failure
    networks:
      - 1panel-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app-green:
    image: sinduke/vaporpreview:latest
    environment:
      DATABASE_HOST: 1Panel-postgresql-jrTE
      DATABASE_NAME: vapor_database
      DATABASE_USERNAME: user_3nr7F8
      DATABASE_PASSWORD: password_FnaEAc
      TZ: Asia/Shanghai
    ports:
      - "8081:8080"
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
    restart: on-failure
    networks:
      - 1panel-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  1panel-network:
    external: true