# 使用官方 PostgreSQL 镜像
FROM postgres:latest

# 设置环境变量
ENV POSTGRES_DB=vapor_database
ENV POSTGRES_USER=vapor_username
ENV POSTGRES_PASSWORD=vapor_password
ENV TZ=Asia/Shanghai

# 暴露 PostgreSQL 默认端口
EXPOSE 5432