name: Fancy Deploy Trigger

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed ]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4

      - name: 🧬 Fancy Deploy with Docker
        uses: ./.github/actions/fancy-deploy
        with:
          server: "47.236.41.229"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          dingtalk-webhook: ${{ secrets.DINGTALK_WEBHOOK }}
          openai-key: ${{ secrets.DEEPSEEK_API_KEY }}
          docker-image-tag: "sinduke/vaporpreview:latest"